#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99
STOP=10

PROG=/usr/sbin/cloudflare-ddns-wrapper

start_service() {
	. /lib/functions.sh

	config_load cloudflare-ddns
	config_get_bool enabled main enabled 0
	[ "$enabled" = "1" ] || return 0

	local api_token zone_id record_name
	config_get api_token   main api_token   ''
	config_get zone_id     main zone_id     ''
	config_get record_name main record_name ''

	if [ -z "$api_token" ] || [ -z "$zone_id" ] || [ -z "$record_name" ]; then
		echo "cloudflare-ddns: api_token, zone_id, record_name must be set in /etc/config/cloudflare-ddns" >&2
		return 1
	fi

	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn
	procd_close_instance
}
