#!/bin/sh
chmod +x /etc/init.d/cloudflare-ddns
/etc/init.d/cloudflare-ddns enable
echo "cloudflare-ddns installed."
echo "Edit /etc/config/cloudflare-ddns to configure, then run:"
echo "  /etc/init.d/cloudflare-ddns start"
